# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in encrypt.gemspec
gemspec

group :development, :test do
  gem "rspec", "~> 3.0"
  gem "pry", "~> 0.14"
  gem "rubocop", "~> 1.0"
end
